name: Main

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
      - '!develop'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: cd example && flutter build apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: cd example && flutter packages get && flutter build windows -v

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter config --enable-macos-desktop
      - run: cd example && flutter packages get && flutter build macos -v

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: cd example && flutter build linux -v